name: Run reproducer on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: help --info
    - name: Execute Gradle build projectA
      run: ./gradlew :projectA:build
    - name: Execute Gradle build projectB
      run: ./gradlew :projectB:build
    - name: Execute Gradle build projectC
      run: ./gradlew :projectC:build
    - name: Execute Gradle build projectD
      run: ./gradlew :projectD:build